Move creating appeal table to a Laravel job
UTRS2/utrs pull request #289
Opened 2020-09-11 15:21 UTC by supertassu

closes #141

2020-11-18 14:01 UTC, supertassu commented on app/Console/Kernel.php
> +        $schedule->command('utrs-jobs:update-appeal-tables --wiki=enwiki')->everyThirtyMinutes();
not sure if this is ok or should it be more often

2020-11-18 14:47 UTC, dqwiki requested changes
While I don't think I ever implemented cookie storage on the python task, we do need to be logging in as little as possible. The examples given for addwiki/mediawiki-api do not indicate that this is something that already exists.

https://github.com/addwiki/mediawiki-api#example-usage

See also:
https://phabricator.wikimedia.org/T256533
https://www.mediawiki.org/wiki/API:Login#Additional_notes
https://en.wikipedia.org/wiki/User_talk:AmandaNP#High_DeltaQuadBot_login_rate

2020-11-18 15:07 UTC, dqwiki commented
I just reread #250 I'm assuming that solves the concern and has been merged?

2020-11-18 15:10 UTC, supertassu commented
> I just reread #250 I'm assuming that solves the concern and has been merged?

@dqwiki  IF you're speaking about re-using sessions, nope, but I'm currently working on that. #250 does improve the situation so that UTRS will only log in when it needs to actually write something, otherwise it just uses the API anonymously

2020-11-18 15:44 UTC, supertassu commented
see #347

2021-02-15 03:26 UTC, dqwiki approved these changes
Looks good from a code perspective.

2021-02-15 03:31 UTC, merged