Feature/laravel jobs permission checking
UTRS2/utrs pull request #88
Opened 2020-05-16 12:05 UTC by supertassu

This depends on #33 for MW api base and is part of master task #59.

2020-05-18 09:51 UTC, supertassu reviewed
Noting here that this does not do anything to banned users (yet)

2020-05-20 18:06 UTC, supertassu reviewed
I think that this is ready for review. I have a feeling that I've forgotten something but I can't seem to remember what and it probably wasn't anything major. @dqwiki Please double-check that the logic itself is correct and please ask if you don't understand something.

2020-05-23 18:04 UTC, supertassu commented
... and we need to deal with changes in #136.

I'd much rather have the `user` permission assigned to everybody who exists on that wiki and only give access to users with `admin` permission to make dealing with #140 much easier

2020-05-24 05:45 UTC, dqwiki reviewed
Sorry, forgot to push this

2020-05-24 05:45 UTC, dqwiki commented on app/Jobs/WikiPermission/BaseWikiPermissionJob.php
> +        $wikis = explode(',', $this->user->wikis ?? '');
This can fail. $wikis can have a Null value, a single value, or multiple values.

2020-05-24 05:45 UTC, dqwiki commented
> ... and we need to deal with changes in #136.
> 
> I'd much rather have the `user` permission assigned to everybody who exists on that wiki and only give access to users with `admin` permission to make dealing with #140 much easier

Absolutely fine with that, my hacks on 136 can be changed up as needed.

2020-05-26 15:11 UTC, dqwiki commented on app/Jobs/WikiPermission/BaseWikiPermissionJob.php
> +        $wikis = explode(',', $this->user->wikis ?? '');
I lies.

2020-05-29 20:58 UTC, dqwiki commented on app/User.php
> +use App\MediawikiIntegration\WikiApiUrls;
This doesn't seem to exist and also errors on my terminal as not found.

2020-05-29 20:59 UTC, dqwiki requested changes
Switch to request changes

2020-06-06 20:45 UTC, dqwiki approved these changes

2020-06-06 20:49 UTC, merged